### ISSUE TITLE
Win7打不开。。。

### ISSUE THREAD

**Issue by zhangbo8418** [xiyanxy/BetterJoy_CHS#1]
点击无反应，我下载源码编译提示错误如下：
![BUG](https://user-images.githubusercontent.com/46797568/94757619-54c04d80-03cd-11eb-867d-17fd30a4ab21.png)

**Comment by xiyanxy** [comment]
我使用的是win10，vs2019编译运行的，没有任何报错的。
你试试不使用vscode？

**Comment by zhangbo8418** [comment]
> 我使用的是win10，vs2019编译运行的，没有任何报错的。
> 你试试不使用vscode？

我本身就是VS2019，不是编译报错，用你编译的打不开，然后我就自己编译也是打不开，然后看调试就这个报错。。。这个是调试报错，编译没有问题。。。

**Comment by xiyanxy** [comment]
> > 我使用的是win10，vs2019编译运行的，没有任何报错的。
> > 你试试不使用vscode？
> 
> 我本身就是VS2019，不是编译报错，用你编译的打不开，然后我就自己编译也是打不开，然后看调试就这个报错。。。这个是调试报错，编译没有问题。。。

错看成vscode了，我这边刚clone下来编译调试均无问题，并且可以运行，难道是win7？或者是x86原因？

**Comment by xiyanxy** [comment]
不会是我设置雅黑UI字体原因吗

**Comment by zhangbo8418** [comment]
> 不会是我设置雅黑UI字体原因吗

我又试了下原版，也是同样的问题，点开进程出现一下就消失了，然后调试报这个错误，6.3的没问题。。。

**Comment by xiyanxy** [comment]
> > 不会是我设置雅黑UI字体原因吗
> 
> 我又试了下原版，也是同样的问题，点开进程出现一下就消失了，然后调试报这个错误，6.3的没问题。。。

这我就不太懂了，你看commit吧
![image](https://user-images.githubusercontent.com/45937440/94761307-45460200-03d7-11eb-96bb-5fadf5fa200a.png)
