### ISSUE TITLE
最新版取消了，操作系统光标乱跳

### ISSUE THREAD

**Issue by zousizhe** [xiyanxy/BetterJoy_CHS#4]
雷神G50第三方手柄，开启xinput显示，摇杆会锁定到右上角。win10界面也受影响，关掉xinput模式，模拟器摇杆选择switch模式正常使用，使用在非原装手柄支持选择defaultcalibration之后正常，但是最新版取消了这个选项

**Comment by xiyanxy** [comment]
非常抱歉给你带来麻烦，去使用旧版吧，目前更新只是追寻原作者合并的更新，之后将以测试版形式发布。谢谢
